[package]
name = "configgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
url = "2.5"
urlencoding = "2.1"
qrcode = "0.14.1"
regex = "1.10.3"
