#!/command/with-contenv sh
# shellcheck shell=sh

set -eou pipefail

echo "Starting certbot..."

STAGING_FLAG=""
if [ "${LETSENCRYPT_STAGING}" = "true" ]; then
    echo "Certbot is in staging mode"
    STAGING_FLAG="--staging"
fi

mkdir -p "${CERTBOT_CONFIG_PATH}"
mkdir -p "${CERTBOT_CONFIG_PATH_WWW}"
for domain in "${REALITY_DOMAIN}" "${XHTTP_DOMAIN}"; do
    certbot \
        certonly \
        --non-interactive \
        --keep-until-expiring \
        --renew-with-new-domains \
        --agree-tos \
        --config-dir="${CERTBOT_CONFIG_PATH}" \
        --register-unsafely-without-email \
        --deploy-hook="${PWD}/data/deploy-hook" \
        --webroot \
        --webroot-path="${CERTBOT_CONFIG_PATH_WWW}" \
        ${STAGING_FLAG} \
        -d="${domain}"
done

# The service is now "up" as all certs are in place
fdmove 1 3 echo ""

echo "Certbot completed successfully. Sleeping for 6 hours..."

# Wait for 6 hours before the next renewal
sleep 6h
