services:
  xray:
    build:
      context: .
      dockerfile: Dockerfile
    stop_grace_period: 0s
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./config:/config
    env_file:
      - .env
