#!/command/with-contenv sh
# shellcheck shell=sh

set -eou pipefail

echo "Starting nginx-xray..."

# Load all xray variables from xray-config
# shellcheck disable=SC1090
. "${XRAY_RUNTIME_CONFIG}"

NGINX_CONFIG="${PWD}/data/nginx.conf"

for nginx_template in "${PWD}"/data/*.conf; do
    sed -i "s|{{REALITY_DOMAIN}}|${REALITY_DOMAIN}|g" "${nginx_template}"
    sed -i "s|{{XHTTP_DOMAIN}}|${XHTTP_DOMAIN}|g" "${nginx_template}"
    sed -i "s|{{XHTTP_SELF_DOMAIN}}|${XHTTP_SELF_DOMAIN}|g" "${nginx_template}"
    sed -i "s|{{XRAY_PATH}}|${XRAY_PATH}|g" "${nginx_template}"
    sed -i "s|{{XRAY_XHTTP_PATH}}|${XRAY_XHTTP_PATH}|g" "${nginx_template}"

    sed -i "s|{{REALITY_DOMAIN_PROXY_SITE}}|${REALITY_DOMAIN_PROXY_SITE}|g" "${nginx_template}"
    sed -i "s|{{XHTTP_DOMAIN_PROXY_SITE}}|${XHTTP_DOMAIN_PROXY_SITE}|g" "${nginx_template}"

    sed -i "s|{{CERTBOT_LIVE_CERT_PATH}}|${CERTBOT_LIVE_CERT_PATH}|g" "${nginx_template}"
done

exec s6-notifyoncheck -n 0 \
    nginx -g 'daemon off;' -c "${NGINX_CONFIG}"
